### PR TITLE
[ERP-1978] Reformat and extend ERP events dictionary

### PR DESCRIPTION
**Pull request by mattcoffman**
Link to Jira issue: https://procoretech.atlassian.net/browse/ERP-1978

Our ERP Events Dictionary is missing a handful of events, and it's also difficult to read through since it's mostly just a wall of text. We'd like to give integrators better documentation to make it easier for them to integrate with our platform. This PR reformats the page for (hopefully) improved readability and adds the events we're missing. Some of the major changes are listed below.

- Cutting out unnecessary API examples and replacing them with links to the relevant API documentation instead.
- Adding tables that provide a quick overview of the events available for each entity type.
- Making the events in the dictionary linkable via anchor tags (e.g. adding `#sync_vendors` to the end of the URL).
- Adding documentation for all ERP events listed in this spreadsheet: https://docs.google.com/spreadsheets/d/1wpbDVRzJ4b-9_ZkyIBwEk8gDGfFz1aYZpc7SyU7brCE

**For Reviewers:** The changes in this PR are pretty substantial, so going through them line-by-line will probably be a pain. The easiest way to review is probably just to inspect the docs visually, so if you don't have the `documentation` repo cloned locally feel free to hit me up, I can spin them up for you if you want to walk through them together. Alternatively, I don't think it's too much work to set up the `documentation` repo, so I'm happy to be a second set of eyes on that if anyone needs.

## Testing Notes
- [x] Spin up the ERP Events Dictionary locally and inspect them visually.

### CODE REVIEW

**Review by weijenlarryli — APPROVED** [review]

**Comment by thomascarli** [comment]
@mattcoffman for the action required sections, some of the actions that are required `Y` are technically only required if they have that metadata enabled.  Are you assuming that if an integrator is receiving that particular event, it is required at that point?

**Comment by mattcoffman** [comment]
@thomascarli Yeah, that was my thought process! The event itself may not be required/enabled for everybody, but if your service is receiving it, then these are the actions you need to perform.

**Review by PatrickCook — APPROVED** [review]

**Comment by thomascarli** [comment]
@mattcoffman for `delete_cost_type_assignments` just a note on this one, we should remember to circle back to this because it seems weird that this endpoint in particular requires a user to call the delete endpoint specifically.

**Comment by thomascarli** [comment]
@mattcoffman for this message `The ERP Integration is expected to check the state of the commitment. If the commitment is in a deleted state (e.g. deleted, archived, etc.), it should be marked as unsynced via the [ERP External Data Sync](https://developers.procore.com/reference/rest/v1/erp-external-data?version=1.0#sync-external-data) endpoint...`. Should we be specific here as to what `unsynced` means like `it should be marked as unsynced (removal of origin_id)` or something like that or is that overkill?

**Comment by mattcoffman** [comment]
@thomascarli Not sure... It might not be a bad idea to add a point of clarification around that, but I wonder if that should live with the External Data Details documentation instead of adding it here? I can also imagine a future where integrators hit a dedicated `/unlink` endpoint to unsync records rather than going through the external data API, we've already got a sort of alpha version of that in the status management controller. So it's possible this documentation will change down the road, if we end up consolidating more behavior under status management.

What are your thoughts? I'm not opposed to the language change, I'm good with it either way.

**Review by thomascarli — APPROVED** [review]
really really great work here! 🔥

**Review by sebastianvaldez-procore — APPROVED** [review]

**Pull request merged**
