### PR TITLE
ERP-19977: Update ERP Technical Guide

### PR DESCRIPTION
**Pull request by PatrickCook**
Update ERP Technical Guide

### CODE REVIEW

**Review by mattcoffman — APPROVED** [review]
Looks good!

**Comment by thomascarli** [comment]
I think  for 

> Project User (admin permission) creates a Service Account in the Procore company. A Client ID and Client secret are generated, as well as a Directory record to manage the Service Account’s read/write permissions to all of the tools available on the Procore company

we should advise folks to use DMSA and direct them to that developer documentation

**Comment by thomascarli** [comment]
@PatrickCook I think this is really a great update.  I think my only thoughts were we should direct integrators to use DMSA.

**Review by thomascarli — APPROVED** [review]
awesome!!

**Pull request merged**
